# Aerospace configuration

# General settings
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 10
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Monitor focus 설정
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps settings
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# Key bindings
[mode.main.binding]
# Use Option(Alt) as modifier for Aerospace

# Focus movement (with cross-monitor support)
alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down --boundaries all-monitors-outer-frame'
alt-k = 'focus up --boundaries all-monitors-outer-frame'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

# Monitor focus movement
alt-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around prev'

# Window movement
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Fullscreen toggle
alt-shift-f = 'fullscreen'

# Workspace switching
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

# Terminal command
alt-enter = 'exec-and-forget open -n /Applications/WezTerm.app'