export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

eval "$(/opt/homebrew/bin/brew shellenv)"


# Added by Toolbox App
export PATH="$PATH:/Users/brucechoe/Library/Application Support/JetBrains/Toolbox/scripts"

export PATH="$PATH:/opt/homebrew/Caskroom/flutter/flutter/bin"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# 한글 로케일 설정
export LANG="ko_KR.UTF-8"
export LC_ALL="ko_KR.UTF-8"
